const clickQ = (sel, i=0) => `(()=>{const e=document.querySelectorAll('${sel}')[${i}]; e && e.click();})()`;
module.exports = [
  { name: 'age', url: 'age-gate.html', extraSeed: `localStorage.removeItem('etz_birthdate')`,
    targets: { q: 'أهلاً بيك في اتزان', form: 'اليوم@form, .card, .box, section', go: 'يلا نبدأ' } },
  { name: 'home', url: 'home-kids.html', full: true,
    targets: { bird: '$.bird-zone', pills: '$.pills', tools: '$.tools', water: '$.water', stats: '$.stats', parentBar: '$.parent-bar', askBar: '$.ask-bar' } },
  { name: 'pomodoro', url: 'pomodoro-kids.html',
    extraSeed: `localStorage.setItem('etz_kid_focus', JSON.stringify({startedAt: Date.now()-372000, totalSec: 600, pausedAt: null, pausedMs: 0}))`,
    targets: { scene: '$#scene', timer: '$#clock', note: 'ولي الأمر@div, p' } },
  { name: 'table', url: 'table-kids.html',
    targets: { road: '$.road', morning: '&.slot:1', add: 'زوّد حاجة' } },
  { name: 'stories', url: 'stories-kids.html',
    targets: { list: '&#cards .card:4', chips: '$#chips' } },
  { name: 'story_read', url: 'stories-kids.html', act: clickQ('#cards [data-id], #cards .card, #cards button, #cards a', 5), wait2: 2000 },
  { name: 'games', url: 'games-kids.html', full: true,
    targets: { play: '$.play-left', focus: '&.gcard:4', locked: '&.soon-h, .gcard.lock:3' } },
  { name: 'act', url: 'act.html',
    targets: { warn: '$#kidBuddyNote', box: 'التنفس الصندوقي@.exercise-card', five: 'الحواس الخمس@.exercise-card', relax: 'الاسترخاء العضلي@.exercise-card' } },
  { name: 'rewards', url: 'rewards-kids.html',
    targets: { stars: '$.bal', cartoon: 'ساعة كرتون@.rw' } },
  { name: 'stickers', url: 'stickers-kids.html',
    targets: { grid: '&.st:9' } },
  { name: 'ask', url: 'ask-zanto.html', full: true, act: clickQ('[data-q]', 4), wait2: 1500,
    targets: { locked: 'ليه في ألعاب مقفولة؟@.q', streak: 'إيه الشعلة دي@.q', water: 'ليه لازم أشرب@.q' } },
  { name: 'parent_lock', url: 'parent-home.html', extraSeed: `sessionStorage.removeItem('etz_parent_pass')`,
    targets: { q: '$.b' } },
  { name: 'parent', url: 'parent-home.html', full: true,
    targets: { head: '$header', today: '$#kidToday', week: 'آخر ٧ أيام@section', behavior: '$#behaviorCard', settings: '$#kidSettingsTitle', rewards: '$#rewardsCard', play: '$#playCard', focus: '$#focusMinCard', look: '$#storyLookCard', msg: '$#birdMsgCard', tools: 'أدوات ولي الأمر@section', library: '$a[href="article.html"]', booklets: '$a[href="booklet-store.html"]', consult: '$a[href="ask.html"]' } },
  { name: 'home_msg', url: 'home-kids.html',
    extraSeed: `localStorage.setItem('etz_bird_msg', JSON.stringify({text:'شاطر يا يوسف إنك خلّصت واجبك النهارده، بحبك', tone:'love', at: Date.now()}))`,
    targets: { bird: '$.bird-zone' } },
  { name: 'home_night', url: 'home-kids.html', hour: 21, min: 30, full: true,
    targets: { close: '$#closeCard' } },
];
